<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Rfid.IngestionService-8e77aa29-de12-4c14-aab7-ebf52e8a7cdc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.11" />
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
  </ItemGroup>

</Project>
